### ISSUE TITLE
A question about prior distribution

### ISSUE THREAD

**Issue by NiPeiyuan** [acerbilab/vbmc#9]
Hi!
Thanks for your papers.

I am a new learner about Bayesian Monte Carlo.

After reading your paper, I have a question about Gaussian processes in your paper 'Variational Bayesian Monte Carlo'.

It seems in some old papers(e.g. Ghahramani, Z. & Rasmussen, C. E. (2002) Bayesian Monte Carlo. Advances in Neural Information Processing Systems 15, 505–512.),  Gaussian process is used to estimate likelihood p(D|x). 

But in your paper, it seems you directly estimate p(D,x) using posterior of Gaussian process.

As p(D,x)=p(D|x)*p(x), where p(x) is prior, it seems your method will ignore it?

And is any difference between estimating p(D,x) or estimating p(D|x)? Thanks.

**Comment by lacerbi** [comment]
You can use a Gaussian process to model the (log) likelihood or (log) joint - or other things for that matter.

VBMC chooses to model the log joint, $\log p(D, x)$, because that's what we need to perform Bayesian quadrature to compute the ELBO for the mixture of Gaussians approximation.
VBMC does not ignore the prior. As you stated, $\log p(D,x)= \log p(D|x) + \log p(x)$, where $p(x)$ is the prior over the model parameters; so the prior is part of the target, i.e. the log joint. The "observations" that VBMC receives are observations of the log joint.

Yes, there are many differences in modelling $p(D,x)$ or $p(D|x)$ (and in fact, we model $\log p(D, x)$, which is yet another thing). There is no short list of things, these are very different objects which require different modelling assumptions. For example, the likelihood $p(D|x)$ as a function of $x$ is not a density. On the other hand, $p(D, x)$ is an unnormalized posterior, so it behaves like a density (namely, it integrates to a constant). This matters when choosing your surrogate model: in VBMC, we need to ensure that the GP mean function leads to an integrable target; see also [this paper](https://proceedings.mlr.press/v96/acerbi19a/acerbi19a.pdf)).

**Comment by NiPeiyuan** [comment]
Thanks for your quickly replying!

From your description, my understanding is the reason for you to choose  modelling p(D,x) rather than p(D|x) is that p(D,x) can be integrated to a constant, while p(D|x) cannot, am I right?  (emmm....but i am not clear why p(D|x) is not a density while p(D,x) is)


And I have another problem is that why not use Graussian Process  to  directly predict expected log joint rather than p(D,x):
![image](https://github.com/acerbilab/vbmc/assets/113538796/b39377e7-f0d2-4da4-b47d-6d5b6449e446)
(Maybe the reason is that the  expected log joint is not  an integrable target ?)

Thanks a lot!

**Comment by NiPeiyuan** [comment]
OK，I got it.
Thanks.
